import React from 'react'
import imgLogo from '../images/logo.png'

const PrivacyPolicy = () => {
  return (
    <div className='w-full'>
      <div className='text-color-text py-5 px-0'>
        <div className='w-[%90] max-w-5xl my-0 mx-auto'>
          <p className='text-base font-bold m-0'>Privacy Policy for NotifyPug</p>
        </div>
      </div>
      <div className='pt-5 border-t border-[#eee]'>
        <div className='w-[%90] max-w-5xl my-0 mx-auto'>
          <h1 className='text-4xl font-bold pb-2 text-center'>Privacy Policy</h1>
          <p className='block text-xs pb-1'>Last updated: December 30, 2023</p>
          <p className='block text-base pb-1 pt-4'>This Privacy Policy describes Our policies and procedures on the collection and handling of information when You use the Service and informs You of Your privacy rights.</p>
          <p className='block text-base pb-1'>By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy, as well as the Terms and Conditions.</p>
          <h2 className='text-3xl font-bold pb-2 pt-6'>Interpretation and Definitions</h2>
          <h3 className='text-2xl font-bold pb-[6px] pt-2'>Interpretation</h3>
          <p className='block text-base pb-1'>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          <h3 className='text-2xl font-bold pb-[6px] pt-2'>Definitions</h3>
          <p className='block text-base pb-1'>For the purposes of this Privacy Policy:</p>
          <ul className='block list-disc'>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>Application</strong> refers to NotifyPug, the software program provided by the Company.</p>
            </li>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to NotifyPug.</p>
            </li>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>Country</strong> refers to:  Mexico</p>
            </li>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
            </li>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
            </li>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>Service</strong> refers to the Application.</p>
            </li>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            </li>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
            </li>
          </ul>
          <h2 className='text-3xl font-bold pb-2 pt-6'>Collecting and Using Your Personal Data</h2>
          <h3 className='text-2xl font-bold pb-[6px] pt-2'>Types of Data Collected</h3>
          <h4 className='text-xl font-bold pb-[2px]'>Personal Data</h4>
          <p className='block text-base pb-1'>Personally identifiable information may include, but is not limited to:</p>
          <ul className='block list-disc'>
            <p className='block text-base pb-1'><li className='list-item ml-4'>Usage Data</li></p>
          </ul>
          <h4 className='text-xl font-bold pb-[2px]'>Usage Data</h4>
          <p className='block text-base pb-1'>Usage Data is collected automatically when using the Service.</p>
          <p className='block text-base pb-1'>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
          <p className='block text-base pb-1'>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
          <h3 className='text-2xl font-bold pb-[6px] pt-2'>Use of Your Personal Data</h3>
          <p className='block text-base pb-1'>The Company may use Personal Data for the following purposes:</p>
          <ul className='block list-disc'>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
            </li>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
            </li>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
            </li>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
            </li>
          </ul>
          <h3 className='text-2xl font-bold pb-[6px] pt-2'>Retention of Your Personal Data</h3>
          <p className='block text-base pb-1'>All data collected in the application will be stored internally on your mobile device and there is no backup or publication of the same in any online database. No third party services can access this information.</p>
          <p className='block text-base pb-1'>By uninstalling the app, all stored data will be permanently deleted. There is also the option within the application to delete records at any time.</p>
          <p className='block text-base pb-1'>The application uses third-party services that may collect information to identify you. Below are links to the privacy policy of the third-party service providers used by the application:</p>
          <ul className='block list-disc'>
            <li className='list-item ml-4'>
              <p className='block text-base pb-1'>AdMob: <a href="https://support.google.com/admob/answer/6128543">https://support.google.com/admob</a></p>
            </li>
          </ul>
          <h3 className='text-2xl font-bold pb-[6px] pt-2'>Advertising</h3>
          <p className='block text-base pb-1'>Inside the app you will find ads provided by AdMob. It is an advertising service provided by Google that may collect and use anonymous data to personalize ads for the user. By default, data processing in AdMob is not restricted and personalized ads will be displayed.</p>
          <h3 className='text-2xl font-bold pb-[6px] pt-2'>Delete Your Personal Data</h3>
          <p className='block text-base pb-1'>Our Service provides you with the ability to delete certain information collected during your use and for the operation of the Service.</p>
          <h3 className='text-2xl font-bold pb-[6px] pt-2'>Security of Your Personal Data</h3>
          <p className='block text-base pb-1'>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect records, we cannot guarantee their absolute security.</p>
          <h2 className='text-3xl font-bold pb-2 pt-6'>Children's Privacy</h2>
          <p className='block text-base pb-1'>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
          <h2 className='text-3xl font-bold pb-2 pt-6'>Links to Other Websites</h2>
          <p className='block text-base pb-1'>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
          <p className='block text-base pb-1'>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          <h2 className='text-3xl font-bold pb-2 pt-6'>Changes to this Privacy Policy</h2>
          <p className='block text-base pb-1'>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
          <p className='block text-base pb-1'>You are advised to review this Privacy Policy periodically for any changes.</p>
          <h2 className='text-3xl font-bold pb-2 pt-6'>Contact Us</h2>
          <p className='block text-base pb-1'>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className='block list-disc'>
            <li className='list-item ml-4'><p className='block text-base pb-1'>By email: hardev.app@gmail.com</p></li>
          </ul>
          <img className='mx-auto' src={imgLogo} alt="Logo NotifyPug" />
        </div>
      </div>
    </div>
  )
};

export default PrivacyPolicy;